### ISSUE TITLE
Prepare intermediate presentation

### ISSUE THREAD

**Issue by mathiasslawik** [TU-Berlin-SNET/iosl-2015-osc-tracking#1]
Henning will do it!

**Comment by cesanli** [comment]
I can suggest for our first presentation to use "prezi". It has an active form and can be interesting to explain our roadplan.
Below you can find the link (for students it is for free):
https://prezi.com/

**Comment by mathiasslawik** [comment]
I'd recommend starting first with the structure and content of your presentation, THEN choose a tool.

While Prezi started it all, there are now great HTML5+JavaScript based open source alternatives you should have a look at:
- [RemarkJS](http://remarkjs.com/)
- [Impress.JS](http://bartaz.github.io/impress.js)
- [reveal.js](http://lab.hakim.se/reveal-js/#/)
- [deck.js](http://imakewebthings.com/deck.js)

I'd recommend looking at their websites and browsing through the demos using the :arrow_right: key. You'll be impressed, especially by Impress.JS.

**Comment by henvo** [comment]
@cesanli I would suggest impress.js.. I will set up a repository where we all can work together..

**Comment by mathiasslawik** [comment]
I don't mind, but make sure, that it does not look silly, i.e., that you REALLY need rotating and zooming canvases. For this, please think first about your CONTENT and THEN about your presentation.

Else, it will look stupid and people will think you are using it just for show.
