### ISSUE TITLE
Setup slide framework and basic structure

### ISSUE THREAD

**Issue by henvo** [TU-Berlin-SNET/iosl-2015-osc-tracking#17]
Please setup a framework for our presentation. Choose a good framework and setup a basic structure.

Please provide the framework in an open respository, so everyone can work on their slides.

**Comment by henvo** [comment]
I decided that we use impress.js. But as Mathias said in another issue, we do not want to make it look silly or stupid.
We want a clean and professional presentation. No special effects.

The repository is here: https://gitub.com/henningvogt/osc-milestone-slides.git

**Comment by mathiasslawik** [comment]
You _can_ use special effects, but they should be motivated by your content.

**Comment by henvo** [comment]
The group decided to use a power point presentation as presentation medium.
Repo deleted. Ticket closed.
